// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_boss.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class BossDefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcz-ZRUDmmDpcX6B-S-IkjObq7F64hD7c',
    appId: '1:783199260718:web:54b4032f8a0ae6c7f1cfbf',
    messagingSenderId: '783199260718',
    projectId: 'boss-a35e7',
    authDomain: 'boss-a35e7.firebaseapp.com',
    storageBucket: 'boss-a35e7.appspot.com',
    measurementId: 'G-JWDGZZE5DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBJZCbDBmOwO-WYl234GcfFOlSAd4C2m4',
    appId: '1:783199260718:android:319a52ab43f53920f1cfbf',
    messagingSenderId: '783199260718',
    projectId: 'boss-a35e7',
    storageBucket: 'boss-a35e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2_xo9EtMFJyk_NiEb1sht52D2VW4oSfM',
    appId: '1:783199260718:ios:d947b90ef753c5f6f1cfbf',
    messagingSenderId: '783199260718',
    projectId: 'boss-a35e7',
    storageBucket: 'boss-a35e7.appspot.com',
    iosClientId: '783199260718-b3mhbdr67sf2pv2bratmkjnipu7ciun5.apps.googleusercontent.com',
    iosBundleId: 'kr.co.gtwins.pushy.pushy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2_xo9EtMFJyk_NiEb1sht52D2VW4oSfM',
    appId: '1:783199260718:ios:d947b90ef753c5f6f1cfbf',
    messagingSenderId: '783199260718',
    projectId: 'boss-a35e7',
    storageBucket: 'boss-a35e7.appspot.com',
    iosClientId: '783199260718-b3mhbdr67sf2pv2bratmkjnipu7ciun5.apps.googleusercontent.com',
    iosBundleId: 'kr.co.gtwins.pushy.pushy',
  );
}
