// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_line.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class LineDefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCH5TXDH2D_oL7YjdIAMN2Yf30pHVNhVk',
    appId: '1:863174772760:web:8dd073a3b25636a8e31b6d',
    messagingSenderId: '863174772760',
    projectId: 'line-teacher',
    authDomain: 'line-teacher.firebaseapp.com',
    storageBucket: 'line-teacher.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI35i99cRi-ZZRjp3DDQz6IKO7P2ql90E',
    appId: '1:863174772760:android:3278743641fae973e31b6d',
    messagingSenderId: '863174772760',
    projectId: 'line-teacher',
    storageBucket: 'line-teacher.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGhxI4a0E8LjPnSRhviKP7B0te0khAuE4',
    appId: '1:863174772760:ios:ee660c8828a2f30be31b6d',
    messagingSenderId: '863174772760',
    projectId: 'line-teacher',
    storageBucket: 'line-teacher.appspot.com',
    iosClientId: '863174772760-lmk7362bcqp4b9jh2f8hor9gg79k174p.apps.googleusercontent.com',
    iosBundleId: 'kr.co.gtwins.pushy.pushy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGhxI4a0E8LjPnSRhviKP7B0te0khAuE4',
    appId: '1:863174772760:ios:ee660c8828a2f30be31b6d',
    messagingSenderId: '863174772760',
    projectId: 'line-teacher',
    storageBucket: 'line-teacher.appspot.com',
    iosClientId: '863174772760-lmk7362bcqp4b9jh2f8hor9gg79k174p.apps.googleusercontent.com',
    iosBundleId: 'kr.co.gtwins.pushy.pushy',
  );
}
